config/routes.rb
Rails.application.routes.draw do
  resources :categories

  devise_for :admins
  devise_for :users

  namespace :admin do
      resources :products
    resources :categories
    root "dashboard#main_page"
  end
  resources :tests
  resources :tasks

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  #get "/:locale", to: "welcome#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :admin
  has_many :product_categories
  has_many :categories, through: :product_categories
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = current_admin.products
    @product = Product.new
    respond_to do |format|
      format.html
      format.json { render json: ProductDatatable.new(params) }
    end
  end

  # GET /products/1 or /products/1.json
  def show

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit

  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.admin = current_admin
    respond_to do |format|
      if @product.save
        # format.html { redirect_to admin_product_url(@product), notice: "Product was successfully created." }
        format.html { redirect_to admin_products_url, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :category)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = current_admin.products
  end

  # GET /products/1 or /products/1.json
  def show

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit

  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.admin = current_admin
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :category)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, @product]) do |form| %>
  <% if @product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>

    <div class="name">
      <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
      <%= form.text_field :name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500",
                          placeholder: "Product name",
                          required: "" %>
    </div>

  </div>

  <div>

    <label for="description"
           class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
    <%= form.text_area :description, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500",
                       placeholder: "Description" %>
  </div>

  <div>

    <label for="price" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Price</label>
    <%= form.text_field :price, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500",
                        placeholder: "1000$", required: "" %>
  </div>

  <div>

<!--    <label for="category-create"-->
<!--           class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Category</label>-->
 <%#= form.text_field :category, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500",laceholder: "Category", required: "" %>
    <%= form.fields_for :category do |f| %>
      <%= f.select :categories, Category.pluck(:name, :id), {}, {} %>
    <% end %>

  </div>

  <div class="bottom-0 left-0 flex justify-center w-full pb-4 space-x-4 md:px-4 md:absolute">
    <%= form.submit "Add ProductProduct", class: "text-white w-full justify-center bg-blue-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" %>


  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div class="flex flex-col align-middle justify-center">
  <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl dark:text-white mt-2 ml-2">All products</h1>
  <div class="items-center justify-between block sm:flex md:divide-x md:divide-gray-100 dark:divide-gray-700">
    <div class="flex items-center mb-4 sm:mb-0">

      <div class="flex items-center w-full sm:justify-end">

      </div>
    </div>

    <%= link_to new_admin_product_path do %>
      <button id="createProductButton" class="text-white bg-blue-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800" type="button" data-drawer-target="drawer-create-product-default" data-drawer-show="drawer-create-product-default" aria-controls="drawer-create-product-default" data-drawer-placement="right">
        Add new product
      </button>
    <% end %>
  </div>
  <div class="overflow-x-auto">
    <div class="inline-block min-w-full align-middle">
      <div class="overflow-hidden shadow">
        <div class="m-4">
          <table id="products-datatable" data-source="<%= admin_products_path(format: :json) %>">
            <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Category</th>
              <th>Description</th>
              <th>Price</th>
            </tr>
            </thead>
            <tbody>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: [:admin , @product] %>

<br>

<div>
  <%= link_to "Show this product",  product: [:admin , @product] %> |
  <%= link_to "Back to products", admin_product_path %>
</div>

app/views/admin/products/index.html.erb
<p style="color: green"><%= notice %></p>



<div id="products" class="p-4">
  <%= render partial: 'product' %>
</div>

<script>
    $('#products-datatable').dataTable({
        "serverSide": true,
        "ajax": $('#products-datatable').data('source'),

        "pagingType": "full_numbers",
        responsive: true,
        "columns": [
            {data: "id"},
            {data: "name"},
            {data: "category"},
            {data: "description"},
            {data: "price"}
        ]

    });
</script>

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>
<br>

<div>

  <%= link_to  admin_products_path do %>
    <button id="createProductButton" class="mt-7 text-white bg-blue-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800" type="button" data-drawer-target="drawer-create-product-default" data-drawer-show="drawer-create-product-default" aria-controls="drawer-create-product-default" data-drawer-placement="right">
      back to products
    </button>
  <% end%>
</div>

app/views/admin/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_admin_product_path(@product) %> |
  <%= link_to "Back to products", admin_product_path %>

  <%= button_to "Destroy this product",  admin_product_path(@product), method: :delete %>
</div>